config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'runners#index'
  resources :runners

end

app/models/runner.rb
class Runner < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show, :edit, :update, :destroy]

  # GET /runners
  # GET /runners.json
  def index
    @runners = Runner.order(:id)
  end

  # GET /runners/1
  # GET /runners/1.json
  def show
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  # POST /runners
  # POST /runners.json
  def create
    @runner = Runner.new(runner_params)

    respond_to do |format|
      if @runner.save
        format.html { redirect_to runners_url}
        format.json { render :show, status: :created, location: @runner }
      else
        format.html { render :new }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1
  # PATCH/PUT /runners/1.json
  def update
    puts params
    respond_to do |format|
      if @runner.update(runner_params)
        format.html { redirect_to runners_url}
        format.json { render :show, status: :ok, location: @runner }
      else
        format.html { render :edit }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.json
  def destroy
    @runner.destroy
    respond_to do |format|
      format.html { redirect_to runners_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:short, :long, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemandRun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
	<nav class="light-blue darken-4" role="navigation">
	    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">DemandRun</a>
	    </div>
  	</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/runners/_form.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short %><br>
    <%= f.number_field :short, value: 0 %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.number_field :long, value: 0 %>
  </div>
  <div class="actions">
    <%= f.submit "Create Runner", class: "light-blue darken-4 waves-effect waves-light btn"%>
  </div>
<% end %>

app/views/runners/_show_runner_partial.html.erb
<tr>
  <td><h4><%= runner.name %></h4></td>
  <td>
    <div class="valign-wrapper">
      <div class="inline indent-md valign"> <h3 class=""><%= runner.short %></h3></div>
      <div class="right inline indent-md half-button"><%= form_tag(runner, method: "patch") do %>
        <%= hidden_field_tag("runner[short]", "#{(runner.short+1)}") %>
        <%= button_tag(type: "submit", class: "light-blue darken-4 waves-effect waves-light btn") do %>
            <i class="material-icons">arrow_upward</i>
        <% end %>
      <% end %>
      </div>
    </div>
  </td>
  <td>
    <div class="valign-wrapper">
      <div class="inline indent-md valign"> <h3><%= runner.long %></h3></div>
      <div class="inline indent-md half-button"><%= form_tag(runner, method: "patch") do %>
        <%= hidden_field_tag("runner[long]", "#{(runner.long+1)}") %>
          <%= button_tag(type: "submit", class: "light-blue darken-4 waves-effect waves-light btn") do %>
          <i class="material-icons">arrow_upward</i>
        <% end %>
      <% end %>
      </div>
    </div>
  </td>
</tr>

app/views/runners/index.html.erb
<p id="notice"><%= notice %></p>

<table >
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Runs</th>
      <th>Long Runs</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <%= render partial: "runners/show_runner_partial", locals: {runner: runner} %>
    <% end %>
  </tbody>
</table>


<div class="right valign-wrapper"> <h5 class="hide-on-med-and-down indent-sm">Add runner</h5><a href="<%= new_runner_path %>" class="btn-floating btn-large waves-effect waves-light orange darken-1 horizontal"><i class="material-icons">add</i></a></div>

app/views/runners/runners/_form.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :short %><br>
    <%= f.number_field :short %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.number_field :long %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runners/runners/_show_runner_partial.html.erb
<h5> Runner's partial </h5>
<tr>
  <td><%= runner.name %></td>
  <td><%= runner.short %></td>
  <td><%= runner.long %></td>
</tr>
<tr>
  <td></td>
  <td>
    <%= form_tag(runner, method: "patch") do %>
        <%= hidden_field_tag("runner[short]", "#{(runner.short+1)}") %>
        <%= submit_tag("Increment Short Run Count") %>
    <% end %>
  </td>
  <td>
    <%= form_tag(runner, method: "patch") do %>
        <%= hidden_field_tag("runner[long]", "#{(runner.long+1)}") %>
        <%= submit_tag("Increment Long Run Count") %>
    <% end %>
  </td>
</tr>

app/views/runners/runners/edit.html.erb
<h1>Editing Runner</h1>

<%= render 'form' %>

<%= link_to 'Show', @runner %> |
<%= link_to 'Back', runners_path %>

app/views/runners/runners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Runners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Runs</th>
      <th>Long Runs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <%= render partial: "runners/show_runner_partial", locals: {runner: runner} %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Runner', new_runner_path %>

app/views/runners/runners/new.html.erb
<h1>New Runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/runners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short:</strong>
  <%= @runner.short %>
</p>

<p>
  <strong>Long:</strong>
  <%= @runner.long %>
</p>

<p>
  <strong>Name:</strong>
  <%= @runner.name %>
</p>

<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @runner.name %>
</p>

<p>
  <strong>Short:</strong>
  <%= @runner.short %>
</p>

<p>
  <strong>Long:</strong>
  <%= @runner.long %>
</p>

<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>